services:
  telegram-bot-api:
    container_name: telegram-bot-api
    image: aiogram/telegram-bot-api:8.1
    restart: always
    env_file:
      - .env
    environment:
      - TELEGRAM_STAT=1
      - TELEGRAM_LOCAL=1
      - TELEGRAM_VERBOSITY=1
      - TELEGRAM_MAX_WEBHOOK_CONNECTIONS=100000
      - TELEGRAM_LOG_FILE=/var/log/telegram-bot-api/telegram-bot-api.log
      - TELEGRAM_MAX_CONNECTIONS=1024
    ports:
      - ${TGBOOT_API_HTTP}:8081
      - ${TGBOOT_API_HTTPS}:8082
    volumes:
      - ./data:/var/lib/telegram-bot-api
      - ./logs:/var/log/telegram-bot-api
    networks:
      - app_network
networks:
  app_network:
    name: app_network
    external: true