# FROM https://github.com/donknap/dpanel
version: "3.3"
services:
  dpanel:
    container_name: dpanel
    image: dpanel/dpanel:latest
    restart: always
    stdin_open: true
    tty: true
    ports:
      - ${DPANEL_HTTP_PORT}:80
      - ${DPANEL_HTTPS_PORT}:443
      - ${DPANEL_ADMIN_PORT}:8080
    environment:
      - APP_NAME=${DPANEL_APP_NAME}
    volumes:
      - ./data:/dpanel
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      createdBy: Apps
    networks:
      - app-network
networks:
  app-network:
    external: true
