# FROM https://github.com/louislam/uptime-kuma

services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    ports:
      - ${UPTIMEKUMA_APP_PORT}:3001
    volumes:
      - ./data:/app/data
    network_mode: bridge
networks: {}
