# FROM https://docs.ntfy.sh/
services:
  ntfy:
    container_name: ntfy
    image: binwiederhier/ntfy:latest
    restart: always
    command:
      - serve
    environment:
      - TZ=Asia/Shanghai
    user: 1000:1000
    volumes:
      - ./data/cache/ntfy:/var/cache/ntfy
      - ./data/ntfy:/etc/ntfy
    ports:
      - ${NTFY_APP_PORT}:80
    healthcheck:
      test:
        - CMD-SHELL
        - wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo
          '"healthy"\s*:\s*true' || exit 1
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      createdBy: Apps
    networks:
      - app-network
networks:
  app-network:
    external: true
