# FROM https://github.com/MHSanaei/3x-ui
services:
  3x-ui:
    container_name: 3x-ui
    image: ghcr.io/mhsanaei/3x-ui:latest
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 2053:2053
    volumes:
      - ./db/:/etc/x-ui/
      - ./cert/:/root/cert/
    environment:
      - XRAY_VMESS_AEAD_FORCED=false
networks: {}
