# FROM https://github.com/dani-garcia/vaultwarden

services:
  vaultwarden:
    container_name: bitwarden-rs
    image: vaultwarden/server:latest
    restart: unless-stopped
    ports:
      - ${BITWARDEN_APP_PORT}:80
    volumes:
      - ./data:/data
    network_mode: bridge
networks: {}
