# FROM https://github.com/gethomepage/homepage
version: "3.3"
services:
  homepage:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest
    restart: unless-stopped
    ports:
      - 80:3000
    volumes:
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    labels:
      createdBy: Apps
    networks:
      - app-network
networks:
  app-network:
    external: true
