# FROM https://github.com/ipfs/kubo
version: "3.3"
services:
  kubo:
    container_name: ipfs-kubo
    image: ipfs/kubo:latest
    volumes:
      - ./data/export:/export
      - ./data/ipfs:/data/ipfs
    ports:
      - 4001:4001
      - 4001:4001/udp
      - 127.0.0.1:8080:8080
      - 127.0.0.1:5001:5001
networks: {}
