# FROM https://github.com/icret/EasyImages2.0
version: "3.8"
services:
  easyimage:
    container_name: easyimage
    image: ddsderek/easyimage:v2.8.5
    restart: unless-stopped
    ports:
      - ${EASYIMAGE_APP_PORT}:80
    volumes:
      - ./data/config:/app/web/config
      - ./data/i:/app/web/i
    environment:
      - TZ=Asia/Shanghai
      - PUID=1000
      - PGID=1000
      - DEBUG=false
    labels:
      createdBy: Apps
    networks:
      - app-network
networks:
  app-network:
    external: true
