services:
  open-webui:
    container_name: open-webui
    image: backplane/open-webui:latest
    # image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    hostname: open-webui
    ports:
      - 3000:8080
    # environment:
    #   - OPENAI_API_KEY=sk-xxxx
    #   - OPENAI_API_BASE_URLS=https://api.openai.com
    #   - OLLAMA_BASE_URL=http://172.17.0.1:11434
    volumes:
      - ./ollama:/root/.ollama
      - ./data:/app/backend/data
    network_mode: bridge
    deploy:
      resources:
        reservations:
          memory: 1024M

