# FROM https://github.com/louislam/uptime-kuma
version: "3.8"
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:latest
    restart: unless-stopped
    ports:
      - ${UPTIMEKUMA_APP_PORT}:3001
    volumes:
      - ./data:/app/data
    labels:
      createdBy: Apps
    networks:
      - app-network
networks:
  app-network:
    external: true
