services:
  wikijs:
    container_name: wikijs-app
    image: ghcr.io/requarks/wiki:2
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    deploy:
      resources:
        reservations:
          memory: 128M
    networks:
      - wikijs_network
  postgres:
    container_name: wikijs-db
    image: postgres:15-alpine
    restart: unless-stopped
    logging:
      driver: none
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    volumes:
      - ./pgdb_data:/var/lib/postgresql/data
    networks:
      - wikijs_network
networks:
  wikijs_network:
    name: wikijs_network
    external: true
