# FROM https://github.com/NginxProxyManager/nginx-proxy-manager
version: "3.8"
services:
  nginxpm:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - ${NGINXPM_ADMIN_PORT}:81
      - ${NGINXPM_HTTP_PORT}:80
      - ${NGINXPM_HTTPS_PORT}:443
    volumes:
      - ./data/data:/data
      - ./data/ssl:/etc/letsencrypt
    labels:
      createdBy: Apps
    networks:
      - app-network
networks:
  app-network:
    external: true
