# FROM https://github.com/AlisaAkiron/mcsmanager-image

services:
  mcsm-web:
    container_name: mcsmanager-web
    image: alisaqaq/mcsmanager-web:latest
    restart: unless-stopped
    ports:
      - 23333:23333
    volumes:
      - ./data:/opt/mcsmanager/web/data
    networks:
      - mcsm_network
networks:
  mcsm_network:
    name: mcsm_network
    external: true
